### ISSUE TITLE
Docusaurus plugin not loaded with current version

### ISSUE THREAD

**Issue by crazyfx1** [typedoc2md/typedoc-plugin-markdown#762]
### What package is the bug related to?

docusaurus-plugin-typedoc

### Describe the issue

When you run the example repo of the docusaurus plugin (https://github.com/typedoc2md/docusaurus-plugin-typedoc-example) everthing works fine and the plugin is loaded during `npm start`:
```
[INFO] Starting the development server...
[info] Loaded plugin typedoc-plugin-markdown
[info] Loaded plugin C:\Users\xxx\source\repos\docusaurus-plugin-typedoc-example\typedoc-plugin.mjs
[info] Post render success
[info] Documentation generated at ./docs/api
[SUCCESS] Docusaurus website is running at: http://localhost:3000/
```

But as soon as you update the dependencies (docusaurus-plugin-typedoc, typedoc and typedoc-plugin-markdown) to the current versions, the plugin is not loaded anymore.

```
  "devDependencies": {
    "@docusaurus/module-type-aliases": "3.5.2",
    "@docusaurus/types": "3.5.2",
    "@types/node": "^22.5.4",
    "docusaurus-plugin-typedoc": "1.2.1",
    "typedoc": "0.27.6",
    "typedoc-plugin-markdown": "4.4.1",
    "typescript": "^5.5.4"
  },
```

Log from `npm start`
```
[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at: http://localhost:3000
```

No errors are shown, the plugin is just not loaded.

### TypeDoc configuration

Everything default from the example repo.

### Expected behavior

The plugin should be loaded when using current versions of the plugin.

**Comment by tgreyuk** [comment]
Thanks - this was issue with Windows.  Has been fixed in `docusaurus-plugin-typedoc@1.2.2`. Have updated the example repo.

**Comment by crazyfx1** [comment]
@tgreyuk Thanks for the fix but unfortunately it's still not working. I've tried the updated example project, reinstalled the packages and started the site. The plugin is still not loaded:

```
C:\Users\xxx\source\repos\docusaurus-plugin-typedoc-example>npm run start

> docs-website@0.0.0 start
> docusaurus start

[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at: http://localhost:3000/

√ Client
  Compiled successfully in 548.73ms

client (webpack 5.97.1) compiled successfully
```

**Comment by tgreyuk** [comment]
Sorry - this is a node 18 issue. Will fix.

**Comment by tgreyuk** [comment]
Fixed and tested in windows / node 18 `docusaurus-plugin-typedoc@1.2.3`

**Comment by crazyfx1** [comment]
It works now, thank you very much.
